# --------------------------------------------------------------------
#
# Build branches.
#
# --------------------------------------------------------------------

name: Branch Build
run-name: Branch Build ${{ github.event.head_commit.message }}

on:
  push:
    branches-ignore:
      - main
      - master

permissions:
  contents: write

jobs:

  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Install podman
        run: sudo apt install -y podman

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run unit tests
#       run: make unit-test
        run: make howie

      - name: Build docs
        run: make docs

      # Branch builds do not publish docs
      # -name: Publish Docs

      # TODO: Create a release
