# ----------------------------------------------
#
#
# ----------------------------------------------

name: Build
run-name: Build on branch "${{ github.ref_name }}" - ${{ github.event.head_commit.message }}

on:
  push: # All branches do a build on a push, including main
    paths-ignore:
      - docs/site/**
      - ./version
      - etc/changelog

jobs:

  do-build:
    uses: ./.github/workflows/shared-build.yml
    with:
      do-release: 'no'
      release-level: none
    secrets: inherit  # Pass repository secrets to the shared workflow
