# ----------------------------------------------
#
# Builds all branchs and conditionally performs a release
#
# ----------------------------------------------

name: Build
run-name: Build ${{ github.event.head_commit.message }}

on:
  push:
    branches:
      - CreateReleases
    paths-ignore:
      - docs/site/**
      - ./version
      
  # Allow manually triggering from GitHub Actions tab
  workflow_dispatch:
    
# Sets permissions of the GITHUB_TOKEN to allow writing
# back to the repository (see docs-publish setp below).
permissions:
  contents: write
  
jobs:

  Build:
    runs-on: ubuntu-latest

    # && startsWith(github.event.pull_request.title, 'Release: major') }}

    # startsWith(github.event.pull_request.title, 'Release: major')

    steps:
      - name: Install podman
        run:  sudo apt install -y podman
        
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Run unit tests
        run:  |
          echo make unit-test
          echo "commit message: ${{ github.event.head_commit.message }}"
          echo "executing on branch: ${{ github.ref_name }}"

      - name: Determine if release
        id: test_for_release
        run: |
          if ${{ startsWith(github.event.head_commit.message, 'Release:') }}; then \
              if [[ ${{ github.ref_name == 'CreateReleases' }} ]]; then \
                  echo "do_release=true"  >> ${GITHUB_OUTPUT}; \
              else \
                  echo "do_release=false" >> ${GITHUB_OUTPUT}; \
              fi; \
          fi
          
      - name: Bump major version number
        if: ${{ steps.test_for_release.outputs.do_release }}
        run:  |
          bump_level=$(echo "${{ github.event.head_commit.message }}" | awk '{ print $2 }')
          make BUMP=$bump_level bump-version

      - name: Build docs
        run:  echo make docs

      - name: Publish docs
        run:  echo make docs-publish

      - name: Create tarball
        run:  echo make create-tarball

      - name: Test tarball
        run:  make test-tarball
        
      - name: Checkin docs
        if: ${{ steps.test_for_release.outputs.do_release }}
        # Performs a git checkin on docs.
        # Hence we need the paths-ignore specification
        # at top of this action to prevent a build loop. 
        # Plus needs "contents" permission to write to repo.
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name ${{ github.actor }}
          git add -A docs/site
          echo howie git commit -m "Publish documentation"
          echo howie git push

      - name: Obtain version and tag
        if: ${{ steps.test_for_release.outputs.do_release }}
        run: echo "Obtain version and tag"

      - name: Push tarball to Github Release
        if: ${{ steps.test_for_release.outputs.do_release }}
        run: echo "Pushing tarball to Github Release"
        
      - name: Tag the Release at the current commit
        if: ${{ steps.test_for_release.outputs.do_release }}
        run: echo "Tagging release"
        echo "git tag -a "v1.2.3" -m "Release: $version""
          
