# ----------------------------------------------
#
# Combined workflow to build and release.
#
# If do-release is false (passed in from calling workflow), then a
# regular build is performed.
#
# If do-release is true (passed in from calling workflow), then in
# addition to a regular build, a release is packaged up.
#
# ----------------------------------------------

name: Shared Build
run-name: Shared Build on branch "${{ github.ref_name }}" - ${{ github.event.head_commit.message }}

on:

  workflow_call:
    inputs:
      do-release:
        description: Perform a release in addition to a build
        required: true
        type: boolean
      release-level:
        description: The release level [major, minor, patch]
        required: true
        type: string

permissions:
  contents: write
  id-token: write

jobs:

  shared-build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install podman
        run:  sudo apt install -y podman

      - name: Run unit tests
        run:  make unit-test

      - name: Bump version number (release-only)
        if: ${{ inputs.do-release }}
        run: make BUMP=${{ inputs.release-level }} bump-version

      - name: Build docs
        run:  make docs

      - name: Publish docs
        run:  make docs-publish

      - name: Create changelog (release-only)
        if: ${{ inputs.do-release }}
        run: make update-changelog

      - name: Create tarball
        id: version_info
        run: |
          make create-tarball
          triplet=$(cat version)
          libName=$(cat _build/release/lib-name)
          tarFile=$(cat _build/release/tarfile-name)
          tarFileBase=$(basename $tarFile)
          tagName=v$triplet
          echo "triplet=$triplet"         >> ${GITHUB_OUTPUT}
          echo "libName=$libName"         >> ${GITHUB_OUTPUT}
          echo "tarFile=$tarFile"         >> ${GITHUB_OUTPUT}
          echo "tarFileBase=$tarFileBase" >> ${GITHUB_OUTPUT}
          echo "tagName=v$triplet"        >> ${GITHUB_OUTPUT}

      - name: Test tarball
        run:  make test-tarball

        # Performs a checkin on docs, version file and changelog.
        # Therefore workflow needs "contents" write permission.
      - name: Checkin artifacts (release-only)
        if: ${{ inputs.do-release }}
        run: |
          git config user.name  github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add docs/site version etc/changelog.md
          git commit -m "Release ${{ steps.version_info.outputs.tagName }}"
          git push

      - name: Push tarball to Github Release (release-only)
        if: ${{ inputs.do-release }}
        uses: softprops/action-gh-release@v2
        with:
          files:    ${{ steps.version_info.outputs.tarFile }}
          name:     ${{ steps.version_info.outputs.tagName }}
          tag_name: ${{ steps.version_info.outputs.tagName }}
          body: "Download ${{ steps.version_info.outputs.tarFileBase }}\nFor installing see [Readme](https://github.com/KingSolomon1954/ksl-bash-lib#installation)"
          draft: false
          prerelease: false
